<script>
export default {
  homeText: ['首页', 'Home'],
  exitText: ['退出', 'Exit'],
  exitTipText: ['确定退出登录?', 'To Log Out ?'],
  loginText: ['登录', 'Login'],
  pageText: ['页', ''],
  skuText: ['SKU#', 'SKU#'],
  submitTipText: ['确定提交审核?', 'To Submit Review ?'],
  submitTipText1: ['确定提交?', 'To Submit ?'],
  tipTitle: ['信息提示', 'Notification Message'],
  text1: ['销售发货', 'Fulfillment'],
  text2: ['销售退货', 'SO Returns'],
  text3: ['采购入库', 'PO In'],
  text4: ['采购退货', 'PO Returns'],
  text5: ['调拨', 'Transfer Order'],
  text6: ['库存查询', 'Search'],
  text7: ['盘点', 'Inv Count'],
  text8: ['移库', 'Inv Transfer'],
  text9: ['设置', 'Setting'],
  text10: ['确认', 'OK'],
  text11: ['确定', 'OK'],
  text12: ['取消', 'Cancel'],
  text13: ['返回', 'Back'],
  text14: ['返回首页', 'Back To Home'],
  text15: ['单号', 'Number'],
  text16: ['点数模式', 'Counting Mode'],
  text17: ['扫码模式', 'Scan Mode'],
  text18: ['upc', 'upc'],
  text19: ['批次', 'Batch'],
  text20: ['品名', 'Name'],
  text21: ['69码', '69 Code'],
  text22: ['库位', 'Bin'],
  text23: ['数量', 'Quantity'],
  text24: ['结束扫码', 'End Scan'],
  text25: ['继续扫码', 'Continue'],
  text26: ['提交审核', 'Submit Review'],
  text27: ['提交', 'Submit'],
  text28: ['入库清单', 'Lists'],
  text29: ['上一页', 'Prev'],
  text30: ['下一页', 'Next'],
  text31: ['跳转', 'Go'],
  text32: ['已完成SKU', 'Finished'],
  text33: ['未完成SKU', 'Unfinished'],
  text34: ['已出库', 'Completed'],
  text35: ['待出库', 'Undone'],
  text36: ['出库清单', 'Lists'],
  text37: ['调拨入库', 'Transfer In'],
  text38: ['调拨出库', 'Transfer Out'],
  text39: ['盘点清单', 'Lists'],
  text40: ['销售退货清单', 'Lists'],
  text41: ['库存列表', 'Inventory Lists'],
  text42: ['总SKU/总数量', 'SKU/Amount'],
  text43: ['库存查询', 'Inventory Search'],
  text44: ['暂无数据', 'No Data'],
  text45: ['订单类型', 'Order Type'],
  text46: ['拣货模式', 'Picking Mode'],
  text47: ['面单', 'Label'],
  text48: ['小包发货', 'Small Bag'],
  text49: ['大包发货', 'Big Bag'],
  text50: ['拣选框绑定', 'Pick Box Binding'],
  text51: ['修改密码', 'Change Password'],
  text52: ['数据同步', 'Data Synchronization'],
  text53: ['接口自检', 'Interface Self-test'],
  text54: ['进度', 'Schedule'],
  text55: ['发货任务清单', 'Lists'],
  text56: ['采购退货清单', 'Lists'],
  text57: ['上架清单', 'Lists'],
  text58: ['销售出库清单', 'Lists'],
  text59: ['库存列表', 'Lists'],
  text60: ['采购入库清单', 'Lists'],
  text61: ['已处理SKU', 'Processed'],
  text62: ['待处理SKU', 'Unprocessed'],
  text63: ['入库', 'Stock In'],
  text64: ['已入库数', 'Done'],
  text65: ['待入库数', 'Undone'],
  text66: ['选择单号', 'Select Number'],
  text67: ['选择模式', 'Select Mode'],
  text68: ['当前库存', 'Current Stock'],
  text69: ['请扫描或输入单号', 'Scan Or Enter Number'],
  text70: ['已盘点数', 'Done'],
  text71: ['已退货数', 'Done'],
  text72: ['待退货数', 'Undone'],
  text73: ['编辑', 'Edit'],
  text74: ['发货任务', 'Deliver Task'],
  text75: ['长', 'L'],
  text76: ['宽', 'W'],
  text77: ['高', 'H'],
  text78: ['扫描或输入', 'Scan Or Enter'],
  text79: ['箱唛', 'Box Mark'],
  text80: ['上架', 'Put On Shelves'],
  text81: ['转出库位', 'Out Bin'],
  text82: ['转入库位', 'In Bin'],
  text83: ['移出', 'Out Bin'],
  text84: ['移入', 'In Bin'],
  text85: ['无任务单上架', 'No Number'],
  text86: ['拣选框号', 'Basket Number'],
  text87: ['新密码', 'New Password'],
  text88: ['确认新密码', 'Confirm Password'],
  text89: ['原密码', 'Old Password'],
  text90: ['请输入SKU', 'Enter SKU'],
  text91: ['请先提交或刷新页面后扫描此商品', 'Please scan product after submitting or refreshing the page.'],
  text92: ['商品不在单号内，请检查!', 'Product is not in the order number, please check!'],
  text93: ['退出后，所有信息将被清空!', 'After exiting, all information will be cleared!'],
  text94: ['返回后，所有信息将被清空!', 'After returning, all information will be cleared!'],
  text95: ['回首页后，所有信息将被清空!', 'After returning to the home page, all information will be cleared!'],
  text96: ['确定退出？', 'Exit?'],
  text97: ['数量不能小于零!', 'Quantity cannot be less than zero!'],
  text98: ['此商品已完成!', 'Product has been finished!'],
  text99: ['入库数量不能大于待入数量!', 'Quantity of stock-in cannot exceed the quantity to be stocked-in!'],
  text100: ['提交失败，请重新提交!', 'Submission failed, please resubmit!'],
  text101: ['请先输入单号!', 'Enter Number!'],
  text102: ['upc/sku', 'upc/sku'],
  text103: ['提交数不能超过库存数!', 'Submission quantity cannot exceed the inventory count!'],
  text104: ['此商品已完成!', 'Product has been finished!'],
  text105: ['出库数量不能大于待出库数量!', 'Outbound quantity cannot exceed the quantity to be stocked- out!'],
  text106: ['退货数量不能大于待退数量!', 'Return quantity cannot exceed the quantity to be refunded!'],
  text107: ['转移数量不能大于可转移数量!', 'Transfer quantity cannot exceed the quantity of transferable ones!'],
  text108: ['收货数量不能大于待收数量!', 'Receipt quantity cannot exceed the quantity to be received!'],
  text109: ['请输入库位!', 'Enter Bin!'],
  text110: ['请输入批次!', 'Enter Batch!'],
  text111: ['库位错误，请检查!', 'Bin Error!'],
  text112: ['批次错误，请检查!', 'Batch Error!'],
  text113: ['已提交数', 'Done'],
  text114: ['待提交数', 'Undone'],
  text115: ['本次提交数', 'Done'],
  text116: ['该单已被用户', 'Order has been locked by'],
  text117: ['锁定', ''],
  text118: ['无效单号', 'Invalid number'],
  text119: ['登录仓库与单号仓库不匹配!', 'Login warehouse does not match the order warehouse!'],
  text120: ['商品数量不对，确定提交吗？', 'Quantity is wrong. Sure to submit?'],
  text121: ['没有获取到单号数据', 'No Number Data'],
  text122: ['此单号已录入不可多次录入', 'Order number has been entered already'],
  text123: ['请输入同一物流商的单号', 'Please enter the number of the same logistics company'],
  text124: ['该箱唛已提交，请检查', 'The shipping mark has been submitted, please check!'],
  text125: ['箱唛不在单号内，请检查', 'The shipping mark is not in the order number, please check!'],
  text126: ['此库位的可转移商品数为0！', 'The quantity of transferable items in this location is 0!'],
  text127: ['账号或密码不正确，请检查！', 'The username or password is incorrect, please check!'],
  text128: ['未绑定拣选框', 'Unbound pick box'],
  text129: ['请输入新密码', 'Enter New Password!'],
  text130: ['请再次确认新密码', 'Enter Confirm Password!'],
  text131: ['两次输入密码不一致，请重新输入', 'Passwords are inconsistent, please re-enter'],
  text132: ['请输入upc!', 'Enter UPC!'],
  text133: ['请输入品名!', 'Enter Name!'],
  text134: ['最少输入三个字符!', 'Enter at least three characters!'],
  text135: ['请输入原密码', 'Enter Old Password!'],
  text136: ['获取验证码', 'Security code'],
  text137: ['手机号不能为空', 'Enter Phone!'],
  text138: ['请输入验证码', 'please enter security code'],
  text139: ['成功!', 'Succesfully!'],
  text140: ['连接超时，请检查网络', 'Please Check Your Network'],
  text141: ['系统错误', 'System Mistake'],
  text142: ['请扫描或输入', 'Scan Or Enter']
}
</script>
